spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  profiles:
    default: dev
  liquibase:
    change-log: classpath:db/changelog/master.xml
  sql:
    init:
      mode: never